Fix/ storages and points
pekshevds/web-tracoma pull request #2
Opened 2022-10-08 17:36 UTC by pekshevds

2022-10-13 04:02 UTC, Melevir requested changes

2022-10-13 04:02 UTC, Melevir commented on webapp/db/point/changers.py
> +    for item in kwargs.items():
Тут лучше писать `for key, value in kwargs.items():`

2022-10-13 04:02 UTC, Melevir commented on webapp/db/point/changers.py
> +    except SQLAlchemyError:
Непонятно, в каких случаях может происходить такая ошибка, тут бы хоть коммент подписать. И ты уверен, что внутри трая должны быть обе строки?

2022-10-13 04:02 UTC, Melevir commented on webapp/db/point/changers.py
> +        point.is_mark = True
`is_mark` бы переименовать в `is_deleted`, а то так можно запутаться.

2022-10-13 04:02 UTC, Melevir commented on webapp/db/storage/changers.py
> +from webapp.db.models import Storage, db
Заметил, что содержание этого модуля - почти полная копипаста модуля changers? От этого можно избавиться. Если в субботу напомнишь, могу показать как :)

2022-10-13 04:02 UTC, Melevir commented on webapp/utils.py
> +
Делать `utils.py` – плохая практика, он мгновенно превращается в свалку всего на свете. 

Лучше бахнуть utils как модуль, а в нём сразу заводить субмодули, utils/files.py, utils/text.py и всё такое.

2022-10-13 04:02 UTC, Melevir commented on webapp/utils.py
> +def prepare_point_values(values):
Вообще непонятно, что тут происходит. Какие значения готовит эта функция? Для чего? Что такое values?

2022-10-13 04:02 UTC, Melevir commented on webapp/utils.py
> +def prepare_storage_values(values):
Аналогичные вопросы.

Плюс судя по количеству ифов кажется, что тут живёт бизнес-логика, а не какая-то утилка. Но это не точно.

2022-10-15 08:17 UTC, pekshevds commented on webapp/db/point/changers.py
> +    for item in kwargs.items():
так и сделал

2022-10-15 08:18 UTC, pekshevds commented on webapp/db/point/changers.py
> +    except SQLAlchemyError:
db.session.add(point) это убрал, оставил в исключениях тлько commit

2022-10-15 08:18 UTC, pekshevds commented on webapp/db/point/changers.py
> +        point.is_mark = True
так и сделал

2022-10-15 08:18 UTC, pekshevds commented on webapp/db/storage/changers.py
> +from webapp.db.models import Storage, db
Я переписал чтоб не дублировалось, но напомню

2022-10-15 08:19 UTC, pekshevds commented on webapp/utils.py
> +
Удалил этот модуль и перенес все в forms для каждой сущности

2022-10-17 05:04 UTC, Melevir commented on webapp/__init__.py
>  from webapp.db.models import db
Из init.py хорошо бы вынести весь код. Раньше Фласк предлагал раскладку проекта, в которой апп инициируется в ините, но сейчас это мало где принято.

2022-10-17 05:04 UTC, Melevir commented on webapp/db/crud_utils/__init__.py
> +from sqlalchemy.exc import SQLAlchemyError
Тут тоже посели этот код в crud_utils.py, это более понятный способ раскладки кода.

2022-10-17 05:04 UTC, Melevir commented on webapp/db/crud_utils/__init__.py
> +def update_or_create_item(id: int, db, get_func, Object, **kwargs):
В `Object` ты передаёшь класс, который инстанцируешь, если объекта не существует, но сам по себе это аргумент с классом, поэтому их обычно называют `new_object_class` или типа того. Это не не название класса, чтобы КемелКейсом его писать.

2022-10-17 05:04 UTC, Melevir commented on webapp/db/crud_utils/__init__.py
> +        item = Object()
Кажется, тут на вход обджекту можно передавать `**kwargs` и избавиться от следующего цикла.

2022-10-17 05:04 UTC, Melevir commented on webapp/db/crud_utils/__init__.py
> +def update_or_create_item(id: int, db, get_func, Object, **kwargs):
Ещё тут не хватает аннотаций типов. Они тут посложнее, но ты справишься: у get_func – Callable, а у обджекта – Type.

2022-10-17 05:04 UTC, Melevir commented on webapp/db/crud_utils/__init__.py
> +def update_or_create_item(id: int, db, get_func, Object, **kwargs):
А ещё для таких общих функций уже хорошо бы писать докстрингу – из-за того, что они мета, не всегда просто догадаться что значит какой аргумент. Тут просто потому что функция маленькая, но если бы она была большой – была бы беда.

2022-10-17 05:38 UTC, pekshevds commented on webapp/db/crud_utils/__init__.py
> +        item = Object()
Не понял по поводу избавится от цикла...поясни пожалуйста.

2022-10-17 05:38 UTC, pekshevds commented on webapp/db/crud_utils/__init__.py
> +def update_or_create_item(id: int, db, get_func, Object, **kwargs):
Поправил

2022-10-17 05:38 UTC, pekshevds commented on webapp/db/crud_utils/__init__.py
> +from sqlalchemy.exc import SQLAlchemyError
Поправил

2022-10-17 05:39 UTC, pekshevds commented on webapp/__init__.py
>  from webapp.db.models import db
переименовал в app

2022-10-17 05:39 UTC, pekshevds commented on webapp/db/point/changers.py
> +    for item in kwargs.items():
поправил

2022-10-17 05:40 UTC, pekshevds commented on webapp/utils.py
> +def prepare_point_values(values):
Убрал это вообще

2022-10-17 06:06 UTC, Melevir commented on webapp/db/crud_utils/__init__.py
> +        item = Object()
`item = Object(**kwargs)` – и всё, цикл не нужен

2022-10-17 07:12 UTC, pekshevds commented on webapp/db/crud_utils/__init__.py
> +        item = Object()
Переписал как ты посоветовал, но такая схема прокатывает когда новый объект, а с существующим как? Валит ошибку UNIQUE constraint failed: point.id
Он добавляет объект не как существующий,а  как новый
(sqlite3.IntegrityError) UNIQUE constraint failed: point.id
[SQL: INSERT INTO point (id, title, is_deleted, create_date, update_date, short) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (3, 'voronezh', 0, '2022-10-17 09:57:21.470413', '2022-10-17 09:57:21.470440', 'vrn')]

Делает insert, а нужет update

2022-10-18 04:00 UTC, merged